#if !COMPILER_UDONSHARP && UNITY_EDITOR
using UnityEngine;
using UnityEditor;
using UdonSharpEditor;
namespace TETR04o {
    [CustomEditor(typeof(T04oMultiplayer))]
    public class T04oMultiplayerEditor : Editor
    {
        public override void OnInspectorGUI()
        {
            if (UdonSharpGUI.DrawDefaultUdonSharpBehaviourHeader(target)) return;
            DrawDefaultInspector();

            T04oMultiplayer myTarget = (T04oMultiplayer)target;

            EditorGUILayout.Space();

            if (GUILayout.Button("Get all arcade machines and set ids"))
            {
                myTarget.machines = FindObjectsByType<T04oGameProcess>(FindObjectsSortMode.None);
                SetReferenceAndIDS(myTarget, myTarget.machines);
            }
        }

        public static void SetReferenceAndIDS(T04oMultiplayer myTarget, T04oGameProcess[] machines) {
            byte id = 0;
            foreach (T04oGameProcess machine in machines) {
                Undo.RecordObject(machine, "Set reference to " + myTarget.name + " in " + machine);
                machine.id = id;
                id++;
                machine.main.multiplayer = myTarget;
                EditorUtility.SetDirty(machine.main);
                EditorUtility.SetDirty(machine);
            }
            myTarget.players = new byte[myTarget.machines.Length];
            myTarget.playersAlive = myTarget.players;
            for(int i = 0; i < myTarget.players.Length; i++) {
                myTarget.players[i] = byte.MaxValue;
            }
            EditorUtility.SetDirty(myTarget);
        }
        //Generated by Claude
        public static void SetReferenceAndIDSSerialized(T04oMultiplayer myTarget, T04oGameProcess[] machines) {
            SerializedObject serialized = new SerializedObject(myTarget);
            SerializedProperty machinesProp = serialized.FindProperty("machines");
            SerializedProperty playersProp = serialized.FindProperty("players");
            SerializedProperty playersAliveProp = serialized.FindProperty("playersAlive");
            machinesProp.arraySize = machines.Length;
            byte id = 0;
            
            for (int i = 0; i < machines.Length; i++)
            {
                T04oGameProcess machine = machines[i];
                machinesProp.GetArrayElementAtIndex(i).objectReferenceValue = machine;
                
                SerializedObject machineObj = new SerializedObject(machine);
                SerializedProperty idProp = machineObj.FindProperty("id");
                idProp.intValue = id;
                id++;
                
                SerializedProperty mainProp = machineObj.FindProperty("main");
                if (mainProp.objectReferenceValue != null)
                {
                    SerializedObject mainObj = new SerializedObject(mainProp.objectReferenceValue);
                    SerializedProperty multiplayerProp = mainObj.FindProperty("multiplayer");
                    multiplayerProp.objectReferenceValue = myTarget;
                    mainObj.ApplyModifiedProperties();
                }
                
                machineObj.ApplyModifiedProperties();
            }
            
            playersProp.arraySize = machines.Length;
            playersAliveProp.arraySize = machines.Length;
            
            for (int i = 0; i < machines.Length; i++)
            {
                playersProp.GetArrayElementAtIndex(i).intValue = byte.MaxValue;
                playersAliveProp.GetArrayElementAtIndex(i).intValue = byte.MaxValue;
            }
            
            serialized.ApplyModifiedProperties();
        }
    }
}
#endif
